#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    ftp_host=""
    ftp_port="21"
    ftp_username="admin"
    ftp_password="123456ABC"
