#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    args.ftp_host = "test.rebex.net"
    args.ftp_port = "21"
    args.ftp_username = "demo"
    args.ftp_password = "password"
