#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

ftp_host=
ftp_port=
ftp_username=
ftp_password=

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================
ynh_script_progression "Storing installation settings..."

ynh_app_setting_set --key=ftp_host --value=$ftp_host
ynh_app_setting_set --key=ftp_port --value=$ftp_port
ynh_app_setting_set --key=ftp_username --value=$ftp_username
ynh_app_setting_set --key=ftp_password --value="$ftp_password"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir"

chmod +x $install_dir/ftpgrab

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template="ftpgrab.yml" --destination="$install_dir/ftpgrab.yml"

chmod 644 "$install_dir/ftpgrab.yml"
chown "$app:$app" "$install_dir/ftpgrab.yml"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated systemd config
ynh_config_add_systemd

yunohost service add "$app" --description="Grab your files periodically from a remote FTP or SFTP server" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
